# Welcome to Jekyll!
 
# Website settings
title: "Usman"
description: "Usman Nisar's blog"
keywords: "usman,uga,computer,science,cs"
baseurl: "/"
url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Usman'
  first_name: 'Usman'
  last_name: 'Nisar'
  email: 'usman@uga.edu'
  github_username: 'unisar'
  head_img: 'static/img/landing/usman.png'
  desc: 'I am a first-year PhD student in Computer Science at University of Georgia. My research interests are in Big Data Systems, Data Science, Machine Learning with a focus on Computer Vision.' 

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'


